service: hexagonal-structure-lamda-adnanP
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    TABLE_NAME:
      Ref: productsTable
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - "Fn::GetAtt": [productsTable, Arn]

functions:
  router:
    handler: handler.router
    events:
      - httpApi:
          path: /sellableProduct
          method: get
      - httpApi:
          path: /dynamoDB/{productId}
          method: get
      - httpApi:
          path: /dynamoDB/{productId}
          method: put
      - httpApi:
          path: /dynamoDB
          method: post
      - httpApi:
          path: /dynamoDB/{productId}
          method: delete    
resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: productsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1