service: hexagonal-structure-lamda-adnanP
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    TABLE_NAME:
      Ref: currenciesTable
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - "Fn::GetAtt": [currenciesTable, Arn]

functions:
  stocks:
    handler: handler.stocks
    events:
      - httpApi:
          path: /stocks/{id}
          method: get
      - httpApi:
          path: /stocks
          method: post
resources:
  Resources:
    currenciesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: currenciesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1